### ISSUE TITLE
static builds for windows-x86 doesn't work

### ISSUE THREAD

**Issue by visioforge** [centricular/cerbero#12]
for gstreamer recipe all failed on install step (looks like path problem),
for base plugins all failed on compile step (gst/check/gstcheck.h not found).

> make[3]: Entering directory /c/gstreamer/cerbero/build/sources/windows_x86/gst-
plugins-base-1.0-static-1.10/tests/check'
i686-w64-mingw32-gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../..   -Wno-error  -Ic:/g
streamer/cerbero/build/dist/windows_x86/include -Wall -g -O2 -DWINVER=0x0501 -D_
WIN32_WINNT=0x0501 -DMINGW_HAS_SECURE_API=1   -Wno-error  -fPIC -DPIC -I../../gs
t-libs -I../../gst-libs -Ic:/gstreamer/cerbero/build/dist/windows_x86/include/gl
ib-2.0 -Ic:/gstreamer/cerbero/build/dist/windows_x86/lib/glib-2.0/include  -Ic:/
gstreamer/cerbero/build/dist/windows_x86/include/gstreamer-1.0 -Ic:/gstreamer/ce
rbero/build/dist/windows_x86/include/glib-2.0 -Ic:/gstreamer/cerbero/build/dist/
windows_x86/lib/glib-2.0/include  -DGST_STATIC_COMPILATION -DG_THREADS_MANDATORY
 -DG_DISABLE_CAST_CHECKS -Wall -Wdeclaration-after-statement -Wvla -Wpointer-ari
th -Wmissing-declarations -Wmissing-prototypes -Wredundant-decls -Wundef -Wwrite
-strings -Wformat-nonliteral -Wformat-security -Winit-self -Wmissing-include-dir
s -Waddress -Waggregate-return -Wno-multichar -Wnested-externs   -g    -Ic:/gstr
eamer/cerbero/build/dist/windows_x86/include/gstreamer-1.0 -Ic:/gstreamer/cerber
o/build/dist/windows_x86/include/glib-2.0 -Ic:/gstreamer/cerbero/build/dist/wind
ows_x86/lib/glib-2.0/include  -DGST_TEST_FILES_PATH="\"../../tests/files\"" -DGS
T_CHECK_TEST_ENVIRONMENT_BEACON="\"GST_PLUGIN_LOADING_WHITELIST\"" -UG_DISABLE_A
SSERT -UG_DISABLE_CAST_CHECKS -pthread -Wall -g -O2 -DWINVER=0x0501 -D_WIN32_WIN
NT=0x0501 -DMINGW_HAS_SECURE_API=1   -Wno-error  -fPIC -DPIC -MT elements/elemen
ts_libvisual-libvisual.o -MD -MP -MF elements/.deps/elements_libvisual-libvisual
.Tpo -c -o elements/elements_libvisual-libvisual.o `test -f 'elements/libvisual.
c' || echo './'`elements/libvisual.c
elements/libvisual.c:1:0: warning: -fPIC ignored for target (all code is positio
n independent) [enabled by default]
elements/libvisual.c:21:32: fatal error: gst/check/gstcheck.h: No such file or d
irectory
compilation terminated.
make[3]: *** [elements/elements_libvisual-libvisual.o] Error 1
make[3]: Leaving directory `/c/gstreamer/cerbero/build/sources/windows_x86/gst-p
lugins-base-1.0-static-1.10/tests/check'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/c/gstreamer/cerbero/build/sources/windows_x86/gst-p
lugins-base-1.0-static-1.10/tests'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/c/gstreamer/cerbero/build/sources/windows_x86/gst-p
lugins-base-1.0-static-1.10'
make: *** [all] Error 2
Recipe 'gst-plugins-base-1.0-static' failed at the build step 'compile'

**Comment by visioforge** [comment]
can I disable tests using some way?

**Comment by nirbheek** [comment]
This branch is no longer maintained, please use the upstream master branch: 

https://gitlab.freedesktop.org/gstreamer/cerbero/
