### ISSUE TITLE
Boostrap fails on Windows7 with Python3 and MINGW32 shell

### ISSUE THREAD

**Issue by 79rpm** [centricular/cerbero#13]
Hello,

I am following the documentation to build Gstreamer. I am on Windows 7 with the following configuration:

User@User-PC ~/gstreamer/cerbero
$ python --version
Python 3.7.2

User@User-PC ~/gstreamer/cerbero
$ which python
/c/Python3/python.exe

/////

Please let me know what is missing, the command passed is: python cerbero-uninstalled bootstrap. It has been extremely painful to build Gstreamer on Windows.

(http://blog.nirbheek.in/2016/07/building-and-developing-gstreamer-using.html)
///////

User@User-PC ~/gstreamer/cerbero
$ python cerbero-uninstalled bootstrap
WARNING: Using default configuration because C:/MinGW/msys/1.0/home/User/.cerber
o/cerbero.cbc is missing
Traceback (most recent call last):
  File "C:\MinGW\msys\1.0\home\User\gstreamer\cerbero\cerbero\utils\shell.py", l
ine 169, in check_call
    stderr=open(os.devnull), shell=shell)
  File "c:\Python3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\Python3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cerbero-uninstalled", line 9, in <module>
    main()
  File "C:\MinGW\msys\1.0\home\User\gstreamer\cerbero\cerbero\main.py", line 130
, in main
    Main(sys.argv[1:])
  File "C:\MinGW\msys\1.0\home\User\gstreamer\cerbero\cerbero\main.py", line 54,
 in __init__
    self.load_config()
  File "C:\MinGW\msys\1.0\home\User\gstreamer\cerbero\cerbero\main.py", line 98,
 in load_config
    self.config.load(self.args.config)
  File "C:\MinGW\msys\1.0\home\User\gstreamer\cerbero\cerbero\config.py", line 1
89, in load
    self.do_setup_env()
  File "C:\MinGW\msys\1.0\home\User\gstreamer\cerbero\cerbero\config.py", line 2
08, in do_setup_env
    self.env = self.get_env(self.prefix, libdir, self.py_prefix)
  File "C:\MinGW\msys\1.0\home\User\gstreamer\cerbero\cerbero\config.py", line 2
28, in get_env
    self._perl_version())
  File "C:\MinGW\msys\1.0\home\User\gstreamer\cerbero\cerbero\config.py", line 5
50, in _perl_version
    version = shell.check_call("perl -e 'print \"$]\";'")
  File "C:\MinGW\msys\1.0\home\User\gstreamer\cerbero\cerbero\utils\shell.py", l
ine 174, in check_call
    raise FatalError(_("Error running command: %s") % cmd)
cerbero.errors.FatalError: Fatal Error: Error running command: ['perl', '-e', 'p
rint "$]";']

**Comment by nirbheek** [comment]
> `cerbero.errors.FatalError: Fatal Error: Error running command: ['perl', '-e', 'print "$]";']`

This is the error. Which branch were you building?

**Comment by 79rpm** [comment]
I believe the branch is meson-1.14. I don't think perl is currently installed on mingw32. I need to double check that. I think I missed this here:

Msys/MinGW: http://sourceforge.net/projects/mingw/files/Installer/mingw-get-setup.exe/download
     Install it with **all** the options enabled

Right now I am rebuilding cerberos from the main Gstreamer/Cerbero, I had better luck and went further into the building. Should I keep trying on this fork or stay on Gstreamer/Cerbero. At this point I need to be able to build and design new plugins for Gstreamer on Windows. At the minimum I should be able to compile for new plugins for Windows.

THANK YOU for your help and recommendations. This Gstreamer compilation on Windows is still very much bumpy. I went through Cygwin build, MSYS2, Meson and finally Cerberos...

**Comment by nirbheek** [comment]
If cerbero master works for you, you should continue to use that. If you want to target 1.14, you should use the 1.14 branch in cerbero upstream. The branches on this repository are only useful if you want to build with MSVC.

**Comment by 79rpm** [comment]
Ok thank you for the reply and yes I am interested in getting it to work with MSVC as well. I will close this issue for now.
