### ISSUE TITLE
python2 usage in the readme

### ISSUE THREAD

**Issue by isometriq** [centricular/cerbero#4]
When building with the MSVC toolchain, it appears we need to use python2.
The readme should specify this ?

Also I recall that my Python 2.7 was not added in the PATH (not sure why), but had to do it manually. Maybe that should go in the windows installation checklist ?

**Comment by apenngrace** [comment]
+1, I also had to C:\Python27 to the PATH in Windows.  Also, it would be helpful to show Windows specific syntax such as ```python2 cerbero-uninstalled bootstrap``` rather than the Unix-style syntax ```./cerbero-uninstalled bootstrap```.
