### ISSUE TITLE
Recipe 'gst-libav-1.0' fails at build step 'compile'

### ISSUE THREAD

**Issue by isometriq** [centricular/cerbero#6]
I'm on branch "meson-1.10" and step 79/81 fails

Some warnings above, cause the step to fail:
c:\mingw\msys\1.0\home\daniel\cerbero-1.10\build\mingw\w32\bin\../lib/gcc/i686-w64-mingw32/4.7.3/../../../../i686-w64-mingw32/include/winbase.h:2791:24: note: expected 'PCONDITION_VARIABLE' but argument is of type 'struct pthread_cond_t *'
cc1.exe: some warnings being treated as errors

It may be like the other issue #5 if my path is too long.
I will confirm in the next build iteration.

**Comment by nirbheek** [comment]
Were you able to confirm that?

**Comment by isometriq** [comment]
This path was the one before I use a shorter one, so I think it was the cause.

When I compiled from the other location I also had problem with steps not completing. By cleaning the recipe (not only `cleanone` but also deleting folder in `./build/sources/local/<recipe>` and `./build/sources/windows_x86/<recipe>`), it could complete the recipe compilation and thus all the package.

**Comment by isometriq** [comment]
Since this path length issue will be problematic all the time, I suggest we mention it in the setup readme as a critical step.

**Comment by nirbheek** [comment]
This branch is no longer maintained, please use the upstream master branch: 

https://gitlab.freedesktop.org/gstreamer/cerbero/
