### ISSUE TITLE
Final 'package' step fails

### ISSUE THREAD

**Issue by isometriq** [centricular/cerbero#7]
***** Error running 'package' command:
The following files required by this package are missing:
 lib/gstreamer-1.0/gsttaglib.dll
lib/gstreamer-1.0/gsttaglib.pdb

I'm not sure if its because "webrtc-audio-processing" and "gst-libav" failed and were skipped...
#5 
#6 

Could that be something else ?
Or is that even necessary at that step (if I dont need the installer, but the files)

**Comment by nirbheek** [comment]
That's fine, your environment has the binaries and executables available from each recipe as soon as it finishes building/installing.
